### ISSUE TITLE
Flatpak version not recognised by official KeePassXC-Browser

### ISSUE THREAD

**Issue by diogogomes** [flathub/org.keepassxc.KeePassXC#13]
**Version:** 2.3.0
**OS:**Xubuntu 16.04

**Error:** `Timeout or not connected to KeePassXC`

**Description:**
KeePassXC is dropping support to KeePassHTTP-Connector and implementing [KeePassXC-Browser](https://github.com/keepassxreboot/keepassxc-browser).

KeePassHTTP-Connector worked like expected on flatpak version but KeePassXC-Browser do not recognise that flatpak version is open.

##### (Sorry create this issue here but I think that is related with flatpak container permissions. Tell me if I should open an issue on KeePassXC-Browser browser. Thanks)

**Comment by AsavarTzeth** [comment]
Thank you for reporting this, I suspect you are correct about permissions and did the right thing informing me here.

KeePassXC 2.3 brought a lot of changes to the optional features in the application. Unfortunately, due to a lack of time, I could not test them all at the time. I will look closer into this, and see if it is possible to get it to work.

**Comment by diogogomes** [comment]
Thanks for your answer @AsavarTzeth.

I'll use deb version until there.

> Unfortunately, due to a lack of time, I could not test them all at the time.

Please mention @diogogomes if you need any help to test on xubuntu 16.04, it will be my pleasure.

Thanks

**Comment by Alexander-Wilms** [comment]
Maybe you can use `flatpak run   --log-session-bus  --log-system-bus org.keepassxc.KeePassXC` to narrow down the problem.

**Comment by diogogomes** [comment]
I tried the command that @Alexander-Wilms suggested and I got multiple errors.

Do you need the entire log or only the errors?

I also got `Cannot encrypt message or public key not found. Is native messaging or support for your browser enabled in KeePassXC?` on browser plugin and I don't know if is related.

**Comment by AsavarTzeth** [comment]
> qdbus org.keepassxc.MainWindow /keepassxc org.keepassxc.MainWindow.lockAllDatabases
Service 'org.keepassxc.MainWindow' does not exist.

This seems to be an unrelated bug that needs to be patched. The application id is `org.keepassxc.KeePassXC` and based on my understanding they need to use the full id as a prefix, everywhere.

**Comment by AsavarTzeth** [comment]
That wiki page might not be up-to-date. It seems someone tried to correct the id, at least partly:

> $ grep -r 'org\\.keepassxc\\.' .
./src/gui/MainWindow.h:    Q_CLASSINFO("D-Bus Interface", "org.keepassxc.KeePassXC.MainWindow")
./src/gui/MainWindow.cpp:    dbus.registerService("org.keepassxc.KeePassXC.MainWindow");
./src/gui/org.keepassxc.KeePassXC.MainWindow.xml:  <interface name="org.keepassxc.KeePassXC.MainWindow">
./src/gui/MainWindowAdaptor.h: * Command line was: qdbusxml2cpp -c MainWindowAdaptor -a MainWindowAdaptor.h:MainWindowAdaptor.cpp org.keepassxc.MainWindow.xml
./src/gui/MainWindowAdaptor.h: * Adaptor class for interface org.keepassxc.MainWindow
./src/gui/MainWindowAdaptor.h:    Q_CLASSINFO("D-Bus Interface", "org.keepassxc.MainWindow")
./src/gui/MainWindowAdaptor.h:"  <interface name=\"org.keepassxc.MainWindow\">\n"
./src/gui/MainWindowAdaptor.cpp: * Command line was: qdbusxml2cpp -c MainWindowAdaptor -a MainWindowAdaptor.h:MainWindowAdaptor.cpp org.keepassxc.MainWindow.xml
./src/browser/HostInstaller.cpp:const QString HostInstaller::HOST_NAME = "org.keepassxc.keepassxc_browser";

That last line is of interest though. I wonder if I am going to have to submit id fixing patches every time someone contributes a new feature.

**Comment by AsavarTzeth** [comment]
So after a lot of research, trial and error I have managed to get this working, with some manual workarounds. Unfortunately I cannot make this work automatically out of the box, but I can patch things so some of these steps are not necessary.

1. Once a browser extension is launched it attempts to connect via the [Native Messaging API](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Native_messaging). To put it simple, the browser starts a native application and communicates via stdio (stdin/stdout).

2. This causes problems if, for example, KeePassXC is already open. To prevent potentially losing unsaved changes to a database, a proxy (`keepassxc-proxy`) is used.

    - Communication with the browser extension uses, the Native Messaging API (stdio)
    - Communication with KeePassXC itself uses a unix socket. This socket is provided when `keepassxc` is launched.

    The first thing I had to patch is where the UNIX socket is located. By default it will listen on:
    `$XDG_RUNTIME_DIR/kpxc_server`
     and fallback to:
     `/tmp/kpxc_server`
     To make it work with Flatpak it needs to listen on:
     `$XDG_RUNTIME_DIR/app/org.keepassxc.KeePassXC/kpxc_server`.
     As usual this is meant to ensure there are no conflicts with other applications. This is easily fixed with a patch. No `--filesystem=xdg-run/app/org.keepassxc.KeePassXC` is required.

3. There are still some issues though. KeePassXC will inform the browser extension that the proxy is available at `/app/bin/keepassxc-proxy`. This is false, since that is only available inside the KeePassXC sandbox.

    You can work around this in KeePassXC by navigating to Tools > Settings and configuring a custom proxy location. This brings us to the last issue.

4. As of https://github.com/flatpak/flatpak/pull/1254 (see related issue https://github.com/flatpak/flatpak/issues/1188) it is possible to use a single command as a wrapper for `flatpak run`. However, this only works for the main command, not a second one, i.e. `keepassxc-proxy`.

    The way I worked around this was by manually creating my own wrapper which I called *org.keepassxc.KeePassXC.Proxy* and making it available to $PATH.

    *Substitute `--branch=master` and `--arch=x86_64` as necessary.*

    ```
    #!/bin/sh
    exec /usr/bin/flatpak run --command=keepassxc-proxy --branch=master --arch=x86_64 org.keepassxc.KeePassXC "$@"
    ```

The only way I could even possibly make this work out of the box is by shipping `keepassxc-proxy` as its own application and maybe find some way to patch KeePassXC so that it finds the wrapper instead of `/app/bin/keepassxc-proxy`.

At this time what I can do is push a patch that fixes the UNIX socket location, but that is about it.

**Comment by shieling** [comment]
I have also come across this problem and have searched for a solution. When I could find no solution I found this forum - thanks for clarifying the issue. As a hobbyist I am not sure I fully understand your workaround but will look forward to any progress made on this issue. Thanks.

**Comment by AsavarTzeth** [comment]
Well this is not supposed to be a self help guide, for anyone inexperienced wirh flatpak.

This is an

**Comment by AsavarTzeth** [comment]
Well this isn't meant to be a self help workaround guide for anyone inexperienced with flatpak. It´s mainly meant for myself and other flatpak maintainers. I simply meant to document the issue in more detail.

If you are familiar with building and maintaining a flatpak, is there any section in particular you found unclear? Perhaps I could improve it?

**Comment by diogogomes** [comment]
@AsavarTzeth Thank you for your effort trying to solve this problem.

I've found that most of the issues can be related to the extension because I'm having the same problem with the Deb package.

You can close it if you want and I open another one if this problem persists after Deb package is fixed.

**Comment by AsavarTzeth** [comment]
That is strange, most if not all, issues listed here actually are specific to a sandboxed environment. It should not occur with a regular debian package. In any case, I would like this issue to remain open.

Feel free to inform me if they make any greater or fundamental redesigns of the extension.

**Comment by diogogomes** [comment]
@AsavarTzeth I use containerised tabs on Firefox (I forgot to mention). Maybe that it's the reason for my issues with the extension.

I'll provide more updates about this issue. Thank you

**Comment by diogogomes** [comment]
Just to leave here the issue of KEEPASSXC that may be related to this:

(Unable to connect to KeePassXC-Browser)[https://github.com/keepassxreboot/keepassxc/issues/1559#issuecomment-369508900]

**Comment by diogogomes** [comment]
@AsavarTzeth, after last updates on deb version and Firefox plugin, the integration started worked without any issues but this situation persists on the Flatpak version.

**Comment by AsavarTzeth** [comment]
Fixed in 934f25a6a8e7969735d788cda4655e4dbc1fb8e4.

Things should just work most of the time. However there are some conditions (see commit message).

By default Flatpak uses the system-wide install (`--system`). In that case things should just work.

If one installs the app with `--user` (user specific installation) then you will have to enter a custom proxy path within the application, ex. in this case `/home/<your_user_name>/.local/share/flatpak/exports/bin/org.keepassxc.KeePassXC`.

Let me know if you have any issues.

**Comment by varjolintu** [comment]
By default Firefox will start KeePassXC which is not the correct behaviour.
To fix this and use keepassxc-properly, please see https://github.com/keepassxreboot/keepassxc-browser/issues/297#issuecomment-429235866.

The solution is basically the same one at step 4 https://github.com/flathub/org.keepassxc.KeePassXC/issues/13#issuecomment-372030281.

**Comment by rugk** [comment]
FYI, for everyone following: I have found a working around involving some manual steps you need to do though for KeePassXC<->Firefox communication, if Firefox is flatpaked/sandboxed (works if KeePassXC is sandboxed or not). [Read the full write-up/tutorial here.](https://discourse.flathub.org/t/how-to-run-firefox-and-keepassxc-in-a-flatpak-and-get-the-keepassxc-browser-add-on-to-work/437?u=rugk)
