### ISSUE TITLE
Can not open Attachments

### ISSUE THREAD

**Issue by dermirt** [flathub/org.keepassxc.KeePassXC#14]
C&P from official keepassXC github [issue 1891](https://github.com/keepassxreboot/keepassxc/issues/1891). Looks like it is some kind of flatpak problem?!

I can not open any attachment in my KeepassXC. Within KeepassX it is possible.

## Expected Behavior
Double-click an attachment of an entry should open it.

## Current Behavior
Double-clicking the attachment of an entry leads to nothing happening.
Within Entry edit mode - Advanced - Open attachment leads to "Unable to open attachments: ... Cant open file ..."

## Steps to Reproduce (for bugs)
Way A:
1. Choose entry with attached file
2. Check attachments tab
3. Double click attachment

Way B:
1. Double click entry with attached file (Edit entry mode)
2. Go to advanced
3. Choose attachment
4. Click "Open"

## Context
Opening attachment.

## Debug Info
KeePassXC - Version 2.3.1
Revision: 2fcaeea
Distribution: Flatpak

Libraries:
- Qt 5.10.1
- libgcrypt 1.7.3

Operating system: Linux 4.9.0-6-amd64
CPU architecture: x86_64
Kernel: linux 4.9.0-6-amd64

Enabled extensions:
- Auto-Type
- Browser Integration
- Legacy Browser Integration (KeePassHTTP)
- SSH Agent
- YubiKey

**Comment by AsavarTzeth** [comment]
This is probably an issue with the KeePassXC not being designed to work with portal API's. For example, we have similar issues like #13.

In other words it is something upstream is going to have to learn about and consider during development. Since KeePassXC is officially distributed as a snap, and snaps also are adopting the [xdg-desktop-portal](https://github.com/flatpak/xdg-desktop-portal) API's, there should be no lack of motivation.

Thanks to this issue, I got reminded about this and took the opportunity to inform the upstream developer team and offering my assistance.
