### ISSUE TITLE
All recent builds in Flathub failed

### ISSUE THREAD

**Issue by amtlib-dot-dll** [flathub/org.keepassxc.KeePassXC#18]
https://flathub.org/builds/#/builders/31/builds/173/steps/5/logs/stdio

They failed with such a puzzling message `error: GPG signatures found, but none are in trusted keyring`

It's not your fault @AsavarTzeth anyway :joy: :joy:

**Comment by AsavarTzeth** [comment]
I know, these kinds of issues happens from time to time. Since I made the last update to `master` late last night, I did not notice it until this morning (when `flatpak update` did not find any update).

What I did now was push an empty commit, which will force a rebuild. That seems to be the common workaround.

**Comment by AsavarTzeth** [comment]
Build successful: https://flathub.org/builds/#/builders/2/builds/1424
