### ISSUE TITLE
Unexpected rendering behaviour when using wayland backend

### ISSUE THREAD

**Issue by amtlib-dot-dll** [flathub/org.keepassxc.KeePassXC#3]
My `.local/share/flatpak/overrides/org.keepassxc.KeePassXC` file:
```ini
[Context]
sockets=!x11;wayland;

[Environment]
GDK_BACKEND=wayland
QT_QPA_PLATFORM=wayland
```

Without the override KeePassXC will use X11 as backend and prone to keyloggers

With this override it is usable, but the UI does not redraw sometimes, as below

![image](https://user-images.githubusercontent.com/8613971/35859713-192ddaea-0b7c-11e8-8de5-f5f847944435.png)

Looking for a fix. Thank you very much!

**Comment by AsavarTzeth** [comment]
This was disabled during the initial review process. See [pull request #148](https://github.com/flathub/flathub/pull/148). Specifically this comment, under the first outdated section:

> We've been disabling Qt's Wayland support as it has issues

I never got any details though. It is possible Qt's issues has been solved since then.

It also appears Wayland support recently was [enabled for Telegram](https://github.com/flathub/org.telegram.desktop/commit/c68fc379dc2b267864c6cb20bc0ae7c529bc0e62). Also, see the issue thread: https://github.com/flathub/org.telegram.desktop/issues/24. Unfortunately there are no mentions of the original Wayland issues there either.

**Comment by nedrichards** [comment]
My understanding is that wayland support was turned on in the KDE runtime and that @apol et al believe it to be 'bug reports welcome' rather than 'disable until it's fixed'. So apps can now enable the wayland socket.

**Comment by aleixpol** [comment]
Yes, wayland support is working, only needs `--socket=wayland` to run. If that's not the case we can look into it.

**Comment by AsavarTzeth** [comment]
Well I just tried adding that socket again and the application launches using x11 in my gnome wayland session. Additionally if I force wayland the way described above I only get `Failed to create display (No such file or directory)`.

**Comment by aleixpol** [comment]
I just tested on Plasma Wayland. The application as is doesn't work. If I pass --socket=wayland it starts fine.

**Comment by AsavarTzeth** [comment]
Oh, my bad! It seems at some point I had switched to Xorg and forgotten about it. It works fine, as expected.

On a minor note, it seems to break icon theming, which usually worked with x11.

**Comment by AsavarTzeth** [comment]
Since wayland support is now enabled I am closing this. If you're still experiencing rendering issues, there isn't really anything I can do about it here.
