### ISSUE TITLE
Cursor does not scale properly for HiDPI screens

### ISSUE THREAD

**Issue by articlecat** [flathub/org.keepassxc.KeePassXC#40]
The cursor does not scale properly for HiDPI screens. In GNOME 3.32 and 3.34, with the display set to 200% scale, the cursor is rendered at 25% of its normal size (half height and half width) when it is hovering over the KeePassXC application window. Moving the cursor away from the KeePassXC window restores it to normal size.

This bug affects the KeePassXC Flatpak, but doesn't affect the standard installation or the Snap package under the same conditions.

**Comment by AsavarTzeth** [comment]
I just want to confirm that I do experience this too, only I have no idea why. I cannot see how anything in this repo might cause this. My first guess would be a toolkit or runtime issue.

**Comment by AsavarTzeth** [comment]
I'm not sure when it changed, but I cannot reproduce this anymore. There have been some updates to both the app and my desktop environment since my last comment, but anything could have fixed it.

I am however still experiencing this (apparently randomly) with other applications, some of which are native Arch packages.

@articlecat Are you still experiencing this with 2.5.4 or later?

**Comment by articlecat** [comment]
@AsavarTzeth Thanks for following up. I can confirm this this issue no longer exists for me, either. Although I'm not sure what resolved it, I am happy to see that it is gone.
