### ISSUE TITLE
Native messaging host path is wrong on user install

### ISSUE THREAD

**Issue by ananace** [flathub/org.keepassxc.KeePassXC#41]
As the title says, when installing this Flatpak in the user - or any other that's not system - installation, then the resulting path in the native messaging host file will be wrong.  
At least on Firefox.

Luckily it's an easy fix of specifying the correct path to the export in the Keepass settings, though it'd be nice if there was a notice about this somewhere (a readme in this repo for instance) - or if it was possible to get Keepass to figure out the correct path automatically.

**Comment by AsavarTzeth** [comment]
I am very well aware of this. In fact if you search my patches and commit messages you will find the very same information you just shared with me. It has been on my TODO list to at least document this in the form of a README.md, but I never got around to it.

Unfortunately KeePassXC has no way of knowing this path, since it's outside the sandbox. When I came up with the workaround I had the choice of making it work out the box with only the most common installation, by assuming the default path, or none at all.

The core issue really is that this messaging mechanism really isn't suitable with the sandbox. Ideally browsers would support dbus as an alternative to stdio.

**Comment by AsavarTzeth** [comment]
I have some good news; I think I have found a reliable method of figuring out the path automatically. Either I overlooked something or the contents of /.flatpak-info has changed.

Would you care to help test it, and make sure the Native Messaging Host manifests always update correctly? I have tried it myself with system and user installations and it seems to work fine, but I would like a second opinion before I publish it.

**Comment by runiq** [comment]
@AsavarTzeth I'd like to help test this, but I'm not sure what you want tested exactly.

> I think I have found a reliable method of figuring out the path automatically. Either I overlooked something or the contents of /.flatpak-info has changed.

You're referring to [this patch](https://github.com/flathub/org.keepassxc.KeePassXC/blob/81f7312d16b7f66fd2f5622da750be9aca8a6d6e/patch/keepassxc/0003-Support-KeePassXC-Browser-Flatpak-environments.patch) in which you get the app path from `/.flatpak-info`, right?

**Comment by AsavarTzeth** [comment]
That is correct. I added automatic detection like @ananace suggested, after having found it possible after all. That is what I want tested.

If you could test it with various custom Flatpak installations, like for example USB mounted filesystems that would be much appreciated. If you can break it in a reasonable manner you might have found something.

Man pages:
**flatpak-install(1)**
**flatpak-installations(5)**
