### ISSUE TITLE
KeePassXC no longer respects GTK dark theme

### ISSUE THREAD

**Issue by nirvinm** [flathub/org.keepassxc.KeePassXC#42]
Until my last update, Flatpak-ed KeePassXC respected the system theme (Light/Dark). The current version ignores the setting and always launches the app in light theme.

Environment: Fedora Workstation 30 / GNOME v3.32.2

**Comment by AsavarTzeth** [comment]
At first I tried and failed to reproduce this on Arch Linux / GNOME 3.34.0 (Xorg session). However since this is theming related I then tried to uninstall org.kde.PlatformTheme.QGnomePlatform//5.13 and bingo!

So depending on if your session uses Xorg or Wayland I have to ask, is the 5.13 branch of the relevant platform theme installed?
- [org.kde.PlatformTheme.QGnomePlatform](https://github.com/flathub/org.kde.PlatformTheme.QGnomePlatform)
- [org.kde.WaylandDecoration.QGnomePlatform-decoration](https://github.com/flathub/org.kde.WaylandDecoration.QGnomePlatform-decoration)

It should have been installed automatically with the update, but if it didn't try installing it manually.

**Comment by nirvinm** [comment]
@AsavarTzeth 

Both the packages are installed. I'm on X11 due to issues with Nvidia and Wayland.

**Comment by AsavarTzeth** [comment]
Version 2.6.0 includes a new built-in dark theme that can be manually set. Automatic detection doesn't seem to work, but at least now it is possible to workaround this issue. So I will be closing this when 2.6.0 is available.

**Comment by arielnmz** [comment]
What does the "Automatic" option do anyway? does it look for a specific env var? or maybe a gsetting? I'm using a custom desktop (AwesomeWM) and I have used several hacks from several posts across the internet, but nothing seems to make KeepassXC correctly determine whether it has to use the "dark" theme:


```sh

# Merge xresources if the file exists
if [ -f ~/.Xresources ]; then
  xrdb -merge ~/.Xresources
fi

# Theme properties
xprop -f _GTK_THEME_VARIANT 8u -set _GTK_THEME_VARIANT "dark"
export GTK_THEME=:dark
export GTK_THEME_VARIANT="dark"

# Some tips from here:
# https://wiki.archlinux.org/title/Uniform_look_for_Qt_and_GTK_applications#Flatpak_Qt_apps_do_not_use_Gnome_Adwaita_dark_theme
export QT_QPA_PLATFORMTHEME='gnome'

```
