### ISSUE TITLE
Yubikey is not always detected

### ISSUE THREAD

**Issue by ovz93br43v7** [flathub/org.keepassxc.KeePassXC#48]
Hi,

I tried keepassxc (flatpak) and keepassxc from the official ppa. There seems to be a problem using the flatpak version, see https://github.com/keepassxreboot/keepassxc/issues/4065
From my observation:

using flatpak:
I have the same issue on elemetaryOS (ubuntu linux). But as long as the yubico personalisation tool is installed, the yubikey is detected by keepassXC everytime.
If I uninstall the personalisation tool keepassXC isn't able to find the yubikey anymore.

using ppa version: Yubikey is always detected

**Comment by ovz93br43v7** [comment]
see keepassxreboot/keepassxc#4065

> we do not control the Flatpak distribution and its likely a library issue. They need to include the libykpers-1 library within the flatpak.

**Comment by AsavarTzeth** [comment]
Unfortunately at this time you are required to setup your Yubikey yourself. It is not possible for a Flatpak to setup hardware devices for you.

Specifically, in order to use your Yubikey at all on your system, you are required to install specific udev rules.

- On Arch Linux it is provided by `yubikey-personalization` and installed at `/usr/lib/udev/rules.d/69-yubikey.rules`.
- On Ubuntu it is separated into the `libyubikey-udev` package and installed at `/lib/udev/rules.d/69-yubikey.rules`

When you install `keepassxc` via a regular linux distribution package it will depend upon `yubikey-personalization` (or libyubikey-udev), thus handling this for you.

However, installing udev rules is not possible with Flatpak. That means, at this time, that either the user or the distribution is responsible for installing this.

For more information see: https://github.com/flatpak/flatpak/issues/961

Hopefully you will find this information useful!

**Comment by ovz93br43v7** [comment]
Thank you for your explanation!

**Comment by AsavarTzeth** [comment]
I know this issue is mainly about properly informing the user about any manual steps that needs to be taken. That hasn't changed and ideally I suppose a pop-up or a link to some official documentation should be there.

Still, I'm leaving this closed because 2.6.0 is supposed to improve upon key detection and as I explained above its not really possible to enable it out-of-the-box.
