### ISSUE TITLE
Open files from NAS / webdav resources is not possible

### ISSUE THREAD

**Issue by ovz93br43v7** [flathub/org.keepassxc.KeePassXC#49]
Hi,

I tried keepassxc (flatpak) and keepassxc from the official ppa. There seems to be a problem using the flatpak version due to the fact that I'm unable to open any files from NAS or webdav drives. I just can't see the network drives in the "open file" dialog. All other programs show in the "open file" dialog under "others" all mounted network drives.

I'm using elementaryOS Hera (ubuntu 18.04).
Has anybody a hint how to fix this?

**Comment by AsavarTzeth** [comment]
Ideally we would have a portal interface, as mentioned: https://github.com/flatpak/xdg-desktop-portal/issues/102

One possible workaround is granting access to the gvfs-daemon, by adding `--talk-name=org.gtk.vfs` and `--talk-name=org.gtk.vfs.*` permissions. This seems to work with few caveats. The recently used databases box will get at least two entries, both with document portal paths, for example:

- `/run/user/1000/doc/d95a4cc4/gdrive_test.kdbx`
- `/run/user/1000/doc/d95a4cc4/1f5cTRL8-tXNq1qk9TJI4ZqsuN2oa2V8Q`

Do you think this would this be acceptable? Perhaps it will at least serve as a temporary solution?

During initial testing KeePassXC also continually crashed when saving a remote database, but luckily the recent 2.5.2 update fixed this!

**Comment by ovz93br43v7** [comment]
Thanks again for your effort. Currently I using the ppa version because of this issue [https://github.com/flathub/org.keepassxc.KeePassXC/issues/48](url). I'm new to linux so I don't know how to make this udev thing work and didn't want to damage anything on my system by trying...

Currently I don't store my keepassxc database on webdav anymore because I'm facing another problem which I didn't managed to solve until now: https://elementaryos.stackexchange.com/questions/21837/all-files-on-webdav-resource-are-write-protected

Nevertheless I tried with the flathub version before updating to 2.5.2 today:
- navigate with the file manager to my webdav resource and opening the database
- keepassxc (flathub) opens the the database from such "portal path" `/run/user/1000/doc/xyz1234/my_keepass.kdbx`
- opening this database using this "portal path" with keepassxc (flathub) I can write on my webdav resource, everthing works as expected
- opening this same database from the webdav resource using keepassxc (ppa version) the keepassxc database is write protected



These portal path looking like temporary paths, is there any risk of data loss if the keepassxc database is stored there?

**Comment by AsavarTzeth** [comment]
You are correct, that is a temporary path.

However all changes will be saved to the real file on disk. Sandboxed flatpak apps use these temporary files when they cannot access the real files directly (due to the sandbox). It is a way of letting the user grant access permissions to individual files.

If the real file is write protected though... That might prevent the file from being saved anywhere but the portal path.

The only risk I am aware of is when one creates new databases, where GTK/Gnome users have to be careful. See #27 

What you can do to be sure of no data loss:
1. Start the flatpak version and open any database.
2. Add a new entry and save the database.
3. Close the app and open the same data base using say the ppa provided package.

If the new entry still exist it works as expected. You can reboot in between if you are real paranoid.

**Note: In all cases data loss would be limited to changes. The original file is always kept.**
