### ISSUE TITLE
Flatpak-KeePassXC can no longer open databases on KDE/Manjaro

### ISSUE THREAD

**Issue by ghost** [flathub/org.keepassxc.KeePassXC#53]
Error: the open database dialog can't access anything, the override flatpak command doesn't help.

Error message: "Couldn't create KDE protocol. It's not possible to create a socket for the "file" protocol's I/O-service manager."

I'm on manjaro, the flatpak and system packages are fresh.

**Comment by AsavarTzeth** [comment]
I'm not sure how you help here, not without much more information and more extensive troubleshooting. Since I don't run KDE myself and don't have enough free time I can't do that work.

However there have been a lot of updates since this was opened. Is this still even an issue? or could I close this?
