### ISSUE TITLE
Wrapper script should use "exec"

### ISSUE THREAD

**Issue by darkdragon-001** [flathub/org.keepassxc.KeePassXC#64]
One should use `exec keepassxc "$@"` in the wrapper script. This way, the PID of the script is passed to the KeePassXC command (and no following commands will be executed in the script afterwards).

**Comment by AsavarTzeth** [comment]
Interesting, not that there is much else to execute in the sandbox and the PID doesn't really matter much (except it does for the wrong reasons).

If I were to make this change a funny unintended side effect might be a greater collision chance with StatusNotifierItem. In fact with that feature in mind we currently want a different PID and preferably a higher or even random one. Otherwise I agree with you and originally it likely was an oversight.

See https://github.com/flathub/org.keepassxc.KeePassXC/commit/362a037832c2e653eb2bf98d75eaf352c17ca3c3 for more information.

**Comment by AsavarTzeth** [comment]
Fixed!
