### ISSUE TITLE
KeePassXC cannot execute host commands using "cmd://" in the URL field of a databse entry

### ISSUE THREAD

**Issue by Bob837217** [flathub/org.keepassxc.KeePassXC#66]
## Overview
keepassxc 2.4.3 as installed as a standard deb package works as it should.
keepassxc 2.6.0 as installed from flatpak does not work as it should.  This is a regression.

## Steps to Reproduce
1.  Launch flatpak keepassxc 2.6.0
2. Create a new entry with any description, username, password
3. Edit the URL field and set the following URL text (without surrounding quotes): "cmd://firefox --private-window https://gmail.google.com"
4. Save the new entry
5. Double click to launch the new instance of firefox as Private Browsing Mode (click Yes on the "Execute command?" dialog box first)
6. Observe a new instance of firefox in Private Browsing with the url set to: https://gmail.google.com

## Expected Behavior

After step 5, you should see and instance of firefox in Private Browsing with the url set to: https://gmail.google.com

## Actual Behavior

After step 5 (confirming Yes on the "Execute command?" dialog box) - nothing appears at all

## Context

**Working Version Details**
KeePassXC - Version 2.4.3
Revision: 5d6ef0c

**Regression Version Details**
KeePassXC - Version 2.6.0
Revision: 0765954
Distribution: Flatpak

Operating System: Linux
Desktop Env: Gnome
Windowing System: X11

**Comment by Bob837217** [comment]
I posted this issue to the KeePassXC authors as: https://github.com/keepassxreboot/keepassxc/issues/5182
One of the authors "droidmonkey" commented:
    "We don't maintain the flatpak"

So I posted the same issue here as it appears to be related to sandboxing for flatpak?

**Comment by AsavarTzeth** [comment]
I just want to  clarify that we can't assume this is a regression between versions, because you compared two very different packaging formats. Flatpak is sandboxed and there are many features in KeePassXC that aren't designed with this in mind.

*Of course this is still a regression in the sense that a feature that is intended to work, simply doesn't. But since you compared the two versions next to each other I assume that isn't what you meant.*

Now I'm not that familiar with this feature but from what I have gathered keepassxc is supposed to support execution of arbitrary commands via the URL field? In that case, yes it very much has to do with sandboxing. No Flatpaks are allowed to execute host commands. In fact, those commands aren't even available from inside the container.

If you want a user level workaround it may be possible to use `flatpak-spawn --host` as a prefix for your intended command. If you do you would have to add this override (permission):
```
flatpak override org.keepassxc.KeePassXC --talk-name=org.freedesktop.Flatpak
```
This way you will be able to use `flatpak-spawn` from within the container as a proxy to execute commands on the host, such as `firefox --private-window`.

For more information about this issue on a flatpak level:
- https://github.com/flatpak/xdg-desktop-portal/issues/283

**Comment by Bob837217** [comment]
Thanks for the explanation, AsavarTzeth.  As it's easier for me to just continue using the .deb for now, that's what I will stick with.  Good to know that there is a potential way to resolve this as you have suggested if I ever have to switch back to the flatpak version.  The question is then, how do we communicate this to flatpak users of keepassxc?  Does the keepassxc author need to document this for endusers in their help documents or similar?  Perhaps a popup if keepassxc detects that it's running in a flatpak sandbox?

**Comment by AsavarTzeth** [comment]
I agree, it would be optimal if this was better communicated. Ideally this feature would be disabled (for the time being) and some information would be provided as for why. KeePassXC already does this (or at least did in the past) for a few features when it is compiled as a Snap package. The html based documentation that is shipped with the app should also be adjusted.

As for actually doing it: I'm not the best developer nor do I have the time to implement that myself. I doubt upstream has has much incentive to do the work either, considering they don't even use Flatpak. Of course if someone else decided to do it, and do it well, upstream would likely accept it.

Personally I am very much interested in a better holistic solution (for the browser integration). I hope to see some developments on the flatpak (or even browser) side that would provide better solutions. Of course the question always remains "when?" and so one can only guess if temporary changes such as what you suggests are worth it.

Thank you for reporting this anyhow, you never know what I might decide to attempt, some boring winter evening.
