### ISSUE TITLE
right click options menu leave my Display screen

### ISSUE THREAD

**Issue by morfyum** [flathub/org.keepassxc.KeePassXC#69]
If I press right click on top entries, right-click menu splips out top of screen. Middle, and bottom entries ok, because menu is showed on middle of screen, but top entries not... :/ 

I cant coply Username, and passwords.
I need to resize app to smaller, and move lower of screen for available copy menus.

I have a small screen notebook: 1366x768.
Im using Fedora 32 with Gnome 3.36.x + Wayland.
Version: KeepassXC (Flatpak) version: 2.6.1
Repo: flathub

There was no problem before.

Thanks!

**Comment by AsavarTzeth** [comment]
This sounds like a local wayland issue to me, but I really have no way of knowing for sure.

In my limited experience wayland issues can be sporadic and affect some users, while leaving others unaffected. It also seems to affect pure Qt apps more often but that is again just based on my own experience.

In any case. This is unfortunately not something I can help with, even if I had the knowledge.

**Comment by AsavarTzeth** [comment]
I'm closing this, since it is unlikely to be a packaging issue or anything I can solve.

One thing I can recommend is the use of keyboard shortcuts: CTRL + C and CTRL + B for copying password and username respectively. That way you don't depend on right click in the first place and this should become less of an issue for you!

Feel free to share if this is even an issue any more after all the updates.
