### ISSUE TITLE
Tray Icon didn't work again

### ISSUE THREAD

**Issue by prometoys** [flathub/org.keepassxc.KeePassXC#78]
Hi,

I have KeePassXC 2.6.4 installed on Ubuntu 20.04 with Ubuntu Desktop (Gnome 3.36). The Flatpak KeePassXC doesn't show the tray icon, but I think it worked for a short time. I can see the tray icon when I start KeePassXC from the AppImage.

It doesn't matter how I start the flatpak. I got this error:
`failed to register service "org.kde.StatusNotifierItem-2-1"`

I don't think it is a duplicate of #58, or?

Best

**Comment by AsavarTzeth** [comment]
Odd, I had this tested by a user and that failure makes no sense, considering [that is allowed](https://github.com/flathub/org.keepassxc.KeePassXC/blob/master/org.keepassxc.KeePassXC.yml#L24).

It could be that you are simply having conflicting apps, i.e. another application has already registered with that dbus name. Do you have many other tray icons?

**Comment by AsavarTzeth** [comment]
A more detailed and better worded explanation of the issue with app indicator / tray icons basing their name uniqueness on the pid:
https://github.com/flathub/org.keepassxc.KeePassXC/commit/362a037832c2e653eb2bf98d75eaf352c17ca3c3

The proper solution to this problem, if anything:
https://github.com/flatpak/xdg-desktop-portal/issues/266

**Comment by prometoys** [comment]
Hi,

I use a lot of other flatpaks with app indicators. It seems to be a conflict with [nextcloud desktop app](https://github.com/flathub/com.nextcloud.desktopclient.nextcloud/).


I don't have this problem with any other App then nextcloud. If I start KeePassXC, I get the Tray Icon. If I start Keepass first, Nextcloud doesn't get the NC-trayicon but see the KeepassXC-trayicon.

No matter what I do (e.g. `/usr/bin/flatpak run --own-name=org.kde.StatusNotifierItem-2-2   org.keepassxc.KeePassXC`) it tries to register org.kde.StatusNotifierItem-2-1 with dbus. 

Why don't you use the PID for X in `org.kde.StatusNotifierItem-X-Y`? Isn't that possible with flatpaks?

Let me know, if I can test anything. 

Kind regards

**Comment by AsavarTzeth** [comment]
> Why don't you use the PID for X in org.kde.StatusNotifierItem-X-Y? Isn't that possible with flatpaks?

I just had a look again at: https://freedesktop.org/wiki/Specifications/StatusNotifierItem/StatusNotifierItem/

You are absolutely right: X is the PID and that works just the same with flatpaks. I see that in my last comment i implied that X (the pid) had changed. That was a mistake. It is the "arbitrary numeric unique identifier" set by KeePassXC that changed, i.e. Y and not X.

> I don't have this problem with any other App then nextcloud. If I start KeePassXC, I get the Tray Icon. If I start Keepass first, Nextcloud doesn't get the NC-trayicon but see the KeepassXC-trayicon.

That confirms that you have a collision. What happens is that both applications tries to register with `org.kde.StatusNotifierItem-2-1`, because to both it appears as if PID 2 is unused.

To clarify, collisions happen because StatusNotifierItem relies on the assumption of unique PID's. Since the the introduction of pid namespaces in the kernel (and then containers such flatpak), this is no longer true.

> I use a lot of other flatpaks with app indicators. It seems to be a conflict with nextcloud desktop app.

In a pid namespace the first PID is 1, similar to init. All apps will therefore use PID 2. That means most, if not all flatpaks will conflict, not just nextcloud.

Earlier we just happened to be lucky that KeePassXC used 2 for Y (for whatever reason). Then there is this change, which I suspected would lead to a higher change of this issue:

https://github.com/flathub/org.keepassxc.KeePassXC/commit/945a4bc3ae36f60d9d96ce5b0ff833df58e29544

If I reverted that it would likely result in `org.kde.StatusNotifierItem-3-1` being used instead.

**Comment by qwertfisch** [comment]
So, what can be done to solve the issue? What part of the system is responsible and needs to be fixed? I have no experience in Flatpak, but from what I read here, this seems to be a flaw for all Flatpak apps using a tray icon.

Why is there a generic name used instead of a truly unique application name (org.keepasxc.KeePassXC for example)? Relying on some kind of a PID which can (and now will) cause conflicts seems error-prone. Is the Flatpak protocol/system responsible? Is it Nextcloud using a string like `org.kde.*` for [this line](https://github.com/flathub/com.nextcloud.desktopclient.nextcloud/blob/master/com.nextcloud.desktopclient.nextcloud.yml#L25)?

**Comment by AsavarTzeth** [comment]
@qwertfisch Its a well known limitation (or flaw, if you will) of the current freedesktop standard, which was written well before sandboxed applications was considered.

That said, disregarding flatpak, in practice we don't really have a universal tray icon standard on Linux. Although most use the kde implementation as you may have noticed.

I strongly recommend this blog post for more info: https://blog.tingping.se/2019/09/07/how-to-design-a-modern-status-icon.html

Ideally, all linux desktop parties would discuss a new standard.

What we need is a dbus service that doesn't rely on ownership of the desktop namespace: org.freedesktop.*, com.canonical.*, or org.kde.* and instead uses the app namespace (org.keepassxc.KeePassXC).

**Comment by qwertfisch** [comment]
Thank you for your patience, the explanation and the blog post. This is very interesting for me, coming from development on Windows systems.
On this particular issue I am now using the AppImage version of Nextcloud which seems to get along with KeepassXC tray icon.

**Comment by AsavarTzeth** [comment]
Yeah this is one of those areas where Windows (and others) does have an advantage. At least to a degree. I mean on Linux desktop environments are even split on whether to keep tray icons, or not.

Yes, from a "it simply works" user perspective using an alternative app distribution makes sense in your case (if you rely on tray icons).

Hopefully tray icons are properly solved one day.

**Comment by ilya-fedin** [comment]
Here's a workaround I developed some time ago:
```
flatpak install org.kde.PlatformTheme.QtSNI
flatpak override --env=QT_QPA_PLATFORMTHEME=qtsni
```

This is a custom SNI implementation that doesn't register unique bus name.

**Comment by droidmonkey** [comment]
Works just fine in latest release on Gnome
