### ISSUE TITLE
Can't save attachments.

### ISSUE THREAD

**Issue by jtagcat** [flathub/org.keepassxc.KeePassXC#79]
Platform: Fedora KDE

Clicking save leads to this:
![image](https://user-images.githubusercontent.com/38327267/112187980-7ec72f80-8bfa-11eb-83b0-03d279518bf1.png)
After entering something to the empty filename, still can't save:
![image](https://user-images.githubusercontent.com/38327267/112188025-88e92e00-8bfa-11eb-96e8-dbfd74c1cd34.png)

**Comment by Neikius** [comment]
Same here. Problem is this looks like an open dialog not save. Title is correct though,

Also verified permissions using flatseal and it is set to "all system files" AND the folder in question was added by me to test. Still same issue.

Installing it via package manager is a serious hassle since I am running a transactional OS.

KeePassXC - 2.6.6
Rev: 9c108b9
Distribution: Flatpak

Qt 5.15.3
Debugging mode is disabled.

**Comment by droidmonkey** [comment]
Works with latest release
